# https://www.opensour.cc/os/virtualization/docker/start
# https://www.opensour.cc/os/virtualization/docker/install/ubuntu
#
# http://www.ansible.com/2014/02/12/installing-and-building-docker-with-ansible
#
# Install Ansible Ubuntu role using either:
#
# git clone https://github.com/angstwad/docker.ubuntu.git
# ansible-galaxy install angstwad.docker_ubuntu
#
# Run:
# ansible-playbook docker.yml --extra-vars='target=SERVER'

---

- hosts: '{{ target }}'
  become: yes
  become_user: root

  roles:
     - angstwad.docker_ubuntu
